[target.aarch64-linux-android]
ar = 'D:/software/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe'
linker = 'D:/software/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd'
rustflags = [
    "-Clink-arg=-landroid",
    "-Clink-arg=-llog",
    "-Clink-arg=-lOpenSLES",
]

[target.armv7-linux-androideabi]
ar = 'D:/software/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe'
linker = 'D:/software/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi24-clang.cmd'
rustflags = [
    "-Clink-arg=-landroid",
    "-Clink-arg=-llog",
    "-Clink-arg=-lOpenSLES",
]

[target.x86_64-linux-android]
ar = 'D:/software/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe'
linker = 'D:/software/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android24-clang.cmd'
rustflags = [
    "-Clink-arg=-landroid",
    "-Clink-arg=-llog",
    "-Clink-arg=-lOpenSLES",
]


[build]
target = "aarch64-linux-android"
